name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: API:Build
      working-directory: ./api
      run: cargo build --verbose
    - name: API:Run-Tests
      working-directory: ./api
      run: cargo test --verbose
